name: Coverage CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install lcov
      run: sudo apt-get install lcov
    - name: prepare
      run: aclocal && autoheader && autoconf && automake --add-missing
    - name: generate
      run: make -f Makefile.cov csvtools.info
      working-directory: cov
    - name: upload
      run: CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }} bash <(curl -s https://codecov.io/bash)
      working-directory: cov
